MVC-GRID/Models/Address.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MVC_GRID.Models
{
    [Table("Addresses")]
    public class Address
    {
        [Key,DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [StringLength(250, ErrorMessage = "Maximum 250 character."), Required]
        public string Name { get; set; }
    }
}

MVC-GRID/Models/Country.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MVC_GRID.Models
{
    [Table("Countries")]
    public class Country
    {
        [Key,DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [StringLength(50, ErrorMessage = "Maximum 50 character."), Required]
        public string Name { get; set; }
        public List<User> Users { get; set; }
    }
}

MVC-GRID/Models/Manager/DatabaseContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
namespace MVC_GRID.Models.Manager
{
    public class DatabaseContext:DbContext
    {
        public DbSet<User> Users { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<Address> Addresses { get; set; }
        public DatabaseContext()
        {
            Database.SetInitializer<DatabaseContext>(new Builder());
        }
    }

    public class Builder : CreateDatabaseIfNotExists<DatabaseContext>
    {
        protected override void Seed(DatabaseContext context)
        {
            List<Country> countryList = new List<Country>();
            for (int i = 0; i < 10; i++)
            {
                Country country = new Country();
                country.Name = FakeData.PlaceData.GetCountry();
                countryList.Add(country);
                context.Countries.Add(country);
            }
            context.SaveChanges();

            for (int i = 0; i < 100; i++)
            {
                User user = new User();
                user.Name = FakeData.NameData.GetFirstName();
                user.Surname = FakeData.NameData.GetSurname();
                user.Age = FakeData.NumberData.GetNumber(10,90);

                Random r = new Random();
                int value = r.Next(0, 10);
                user.Country = countryList[value];
                context.Users.Add(user);
            }
            context.SaveChanges();
        }
    }
}

MVC-GRID/Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MVC_GRID.Models
{
    [Table("Users")]
    public class User
    {
        [Key,DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [StringLength(50,ErrorMessage ="Maximum 50 character."),Required]
        public string Name { get; set; }
        [StringLength(50, ErrorMessage = "Maximum 50 character."), Required]
        public string Surname { get; set; }
        public int Age { get; set; }

        public Country Country { get; set; }
    }
}

MVC-GRID/Controllers/GridController.cs
using MVC_GRID.Models;
using MVC_GRID.Models.Manager;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_GRID.Controllers
{
    public class GridController : Controller
    {
        DatabaseContext db = new DatabaseContext();
        // GET: Grid
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List()
        {
            var model = db.Users.ToList();
            return View(model);
        }
        
        public ActionResult Create()
        {
            List<SelectListItem> country = (from i in db.Countries.ToList()
                                            select new SelectListItem
                                            {
                                                Text = i.Name,
                                                Value = i.Id.ToString()
                                            }).ToList();
            ViewBag.countryList = country;
            return View();
        }

        [HttpPost]
        public ActionResult Create(User model)
        {
            var country = db.Countries.Where(m => m.Id == model.Country.Id).FirstOrDefault();
            model.Country = country;
            db.Users.Add(model);
            db.SaveChanges();
            return RedirectToAction("List");
        }

        public ActionResult Edit(int id)
        {
            var user = db.Users.Where(m => m.Id == id).FirstOrDefault();
            List<SelectListItem> country = (from i in db.Countries.ToList()
                                            select new SelectListItem
                                            {
                                                Text = i.Name,
                                                Value = i.Id.ToString()
                                            }).ToList();
            ViewBag.countryList = country;
            return View(user);
        }

        [HttpPost]
        public ActionResult Edit(User model)
        {
            var user = db.Users.Where(m => m.Id == model.Id).FirstOrDefault();
            user.Name = model.Name;
            user.Surname = model.Surname;
            user.Age = model.Age;
            var country = db.Countries.Where(m => m.Id == model.Country.Id).FirstOrDefault();
            user.Country= country;
            db.SaveChanges();           
            return RedirectToAction("List");
        }

        public ActionResult Delete(int? id)
        {
            if (id!=null)
            {
                var user = db.Users.Where(m => m.Id == id).FirstOrDefault();
                if (user!=null)
                {
                    db.Users.Remove(user);

                    int value = db.SaveChanges();
                    if (value>0)
                    {

                    }
                    else
                    {

                    }
                }
            }
            return View();
        }
    }
}

MVC-GRID/Controllers/HomeController.cs
using MVC_GRID.Models.Manager;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_GRID.Controllers
{
    public class HomeController : Controller
    {
        DatabaseContext db = new DatabaseContext();  
        // GET: Home
        public ActionResult Index()
        {
            var value = db.Users.ToList();
            return View();
        }

        public ActionResult List()
        {
            var model = db.Users.ToList();
            return View(model);
        }
    }
}

MVC-GRID/Views/Grid/Create.cshtml
@model MVC_GRID.Models.User
@{
    ViewBag.Title = "Yeni Ekle";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<h2>Yeni Kullanıcı Ekle</h2>

@using (Html.BeginForm())
{
    <div class="input-group">
        <span class="input-group-addon" id="txt_name"><i class="glyphicon glyphicon-user"></i></span>
        @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder = "Adınızı Giriniz", aria_describedy = "txt_name" })
    </div>
    <br />
    <div class="input-group">
        <span class="input-group-addon" id="txt_surname"><i class="glyphicon glyphicon-user"></i></span>
        @Html.TextBoxFor(m => m.Surname, new { @class = "form-control", placeholder = "Soyadınızı Giriniz", aria_describedy = "txt_surname" })
    </div>
    <br />

    <div class="input-group">
        <span class="input-group-addon" id="txt_age"><i class="glyphicon glyphicon-time"></i></span>
        @Html.TextBoxFor(m => m.Age, new { @class = "form-control", placeholder = "Yaşınızı Giriniz", aria_describedy = "txt_age" })
    </div>
    <br />

    <div class="input-group">
        <span class="input-group-addon" id="txt_country"><i class="glyphicon glyphicon-globe"></i></span>
        @Html.DropDownListFor(m => m.Country.Id, (List<SelectListItem>)ViewBag.countryList, new { @class = "form-control", aria_describedy = "txt_country" })
    </div>
    <br />
    <input type="submit" class="btn btn-success" value="Kaydet" />
}

MVC-GRID/Views/Grid/Delete.cshtml
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<h2>Silmek istediğine emin misin?</h2>
@Html.ActionLink("Evet", "List", "Grid", null, new { @class = "btn btn-success" })

MVC-GRID/Views/Grid/Edit.cshtml
@model MVC_GRID.Models.User

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}


<h2 style="text-align:center; font-family:'Times New Roman', Times, serif; margin:25px; ">Kullanıcı Düzenle</h2>

@using (Html.BeginForm())
{
    @Html.HiddenFor(m=>m.Id)
    <div class="input-group">
        <span class="input-group-addon" id="txt_name"><i class="glyphicon glyphicon-user"></i></span>
        @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder = "Adınızı Giriniz", aria_describedy = "txt_name" })
    </div>
    <br />
    <div class="input-group">
        <span class="input-group-addon" id="txt_surname"><i class="glyphicon glyphicon-user"></i></span>
        @Html.TextBoxFor(m => m.Surname, new { @class = "form-control", placeholder = "Soyadınızı Giriniz", aria_describedy = "txt_surname" })
    </div>
    <br />

    <div class="input-group">
        <span class="input-group-addon" id="txt_age"><i class="glyphicon glyphicon-time"></i></span>
        @Html.TextBoxFor(m => m.Age, new { @class = "form-control", placeholder = "Yaşınızı Giriniz", aria_describedy = "txt_age" })
    </div>
    <br />

    <div class="input-group">
        <span class="input-group-addon" id="txt_country"><i class="glyphicon glyphicon-globe"></i></span>
        @Html.DropDownListFor(m => m.Country.Id, (List<SelectListItem>)ViewBag.countryList, new { @class = "form-control", aria_describedy = "txt_country" })
    </div>
    <br />
    <input type="submit" class="btn btn-success" value="Kaydet" />
}

MVC-GRID/Views/Grid/List.cshtml
@model IEnumerable<MVC_GRID.Models.User>
@using GridMvc.Html
@{
    ViewBag.Title = "Kullanıcılar";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<h2 style="text-align:center; font-family:'Times New Roman', Times, serif; margin:25px; ">Kullanıcılar</h2>

@Html.ActionLink("Yeni Ekle","Create","Grid",null,new { @class="btn btn-primary"})

@Html.Grid(Model).Columns(column =>
{
    column.Add(m => m.Name).Titled("Adlar").Sortable(true).Filterable(true);
    column.Add(m => m.Surname).Titled("Soyadlar").Sortable(true).Filterable(true);
    column.Add(m => m.Age).Titled("Yaşlar").Sortable(true).Filterable(true);
    column.Add().Titled("İşlemler")
    .Encoded(false)
    .Sanitized(false)
    .SetWidth(30)
    .RenderValueAs(o => Html.ActionLink("Düzenle", "Edit", "Grid", new { id = o.Id }, new { @class = "btn btn-warning" }));
    column.Add()
    .Encoded(false)
    .Sanitized(false)
    .SetWidth(30)
    .RenderValueAs(o => Html.ActionLink("Sil", "Delete", "Grid", new { id = o.Id }, new { @class = "btn btn-danger" }));
}).WithPaging(10).Sortable(true)

MVC-GRID/Views/Home/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

MVC-GRID/Views/Home/List.cshtml
@model IEnumerable<MVC_GRID.Models.User>

@{
    ViewBag.Title = "Kullanıcılar";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<h2>List</h2> 

<ul class="list-group">
   @foreach (var item in Model)
   {
       <li class="list-group-item">
        @item.Name
       </li>
   }
</ul>

MVC-GRID/Views/Shared/_Grid.cshtml
@using GridMvc.Columns
@model GridMvc.IGrid
@if (Model == null) { return; }
@if (Model.RenderOptions.RenderRowsOnly)
{
    @RenderGridBody();
}
else
{
    <div class="grid-mvc" data-lang="@Model.Language" data-gridname="@Model.RenderOptions.GridName" data-selectable="@Model.RenderOptions.Selectable.ToString().ToLower()" data-multiplefilters ="@Model.RenderOptions.AllowMultipleFilters.ToString().ToLower()">
        <div class="grid-wrap">
            <table class="table table-striped grid-table">
                @* Draw grid header *@
                <thead>
                    @RenderGridHeader()
                </thead>
                <tbody>
                    @RenderGridBody()
                </tbody>
            </table>
            @RenderGridPager()
        </div>
    </div>
}
@helper RenderGridBody()
{
    if (!Model.ItemsToDisplay.Any())
    {
    <tr class="grid-empty-text">
        <td colspan="@Model.Columns.Count()">
            @Model.EmptyGridText
        </td>
    </tr>
    }
    else
    {
        foreach (object item in Model.ItemsToDisplay)
        {
    <tr class="grid-row @Model.GetRowCssClasses(item)">
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.CellRenderer.Render(column, column.GetCell(item))
        }
    </tr>
        }
    }
}
@helper RenderGridHeader()
{
    <tr>
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.HeaderRenderer.Render(column)
        }
    </tr>
}
@helper RenderGridPager()
{
    if (Model.EnablePaging && Model.Pager != null)
    {
    <div class="grid-footer">
        @Html.Partial(Model.Pager.TemplateName, Model.Pager)
    </div>
    }
}

MVC-GRID/Views/Shared/_GridPager.cshtml
@model GridMvc.Pagination.GridPager
@if (Model == null || Model.PageCount <= 1)
{
    return;
}
<div class="grid-pager">
    <ul class="pagination">
        @if (Model.CurrentPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(Model.CurrentPage - 1)">«</a>
            </li>
        }

        @if (Model.StartDisplayedPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(1)">1</a>
            </li>
            if (Model.StartDisplayedPage > 2)
            {
            <li><a href="@Model.GetLinkForPage(Model.StartDisplayedPage - 1)">...</a></li>
            }
        }
        @for (int i = Model.StartDisplayedPage; i <= Model.EndDisplayedPage; i++)
        {
            if (i == Model.CurrentPage)
            {
            <li class="active"><span>@i</span></li>
            }
            else
            {
            <li><a href="@Model.GetLinkForPage(i)">@i</a></li>
            }
        }
        @if (Model.EndDisplayedPage < Model.PageCount)
        {
            if (Model.EndDisplayedPage < Model.PageCount - 1)
            {
            <li><a href="@Model.GetLinkForPage(Model.EndDisplayedPage + 1)">...</a></li>
            }
            <li><a href="@Model.GetLinkForPage(Model.PageCount)">@Model.PageCount</a></li>
        }
        @if (Model.CurrentPage < Model.PageCount)
        {
            <li><a href="@Model.GetLinkForPage(Model.CurrentPage + 1)">»</a></li>
        }
    </ul>
</div>

MVC-GRID/Views/Shared/_LayoutPage.cshtml
<!DOCTYPE html>

<html>

<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/Gridmvc.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.6.0.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/gridmvc.min.js"></script>
</head>

<body>
    <div class="container">
        <div class="col-md-3">

        </div>
        <div class="col-md-7">
            @RenderBody()
        </div>
    </div>
</body>
</html>